#!/bin/bash
# Extracts and formats Pokémon info from data.json using only jq, awk, and sed
jq -r '
  .[] |
  "\(.name) \(.types | map(.type.name) | join(",")) \(.weight) \(.height)"
' data.json | \
printf "%s is of type %s, weighs %skg, and is %sm tall.\n", name, type_str, weight, height"